proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
# importamos el login requerido para el inicio de sesion
from django.contrib.auth.decorators import login_required
# importamos inicio y paginas de errores 404
from app.views import Inicio
# importamos para el inicio de sesion y el cierre de sesion
from usuario.views import Login, logoutUsuario

urlpatterns = [
    path('admin/', admin.site.urls),
    path('minhvi/', include('app.urls')),
    path('usuario/', include('usuario.urls')),
    path('', login_required(Inicio.as_view()),name="index"),
    # ruta del login
    path('accounts/login/', Login.as_view()),
    # ruta del logout
    path('logout/', login_required(logoutUsuario), name='logout'),
]

usuario/urls.py
"""Importamos los VIEWS creados en VIEWS.PY

    from django.urls: Importamos el PATH
    from django.contrib.auth.decorators: Login_required
    from .views: Importamos los VIEWS de VIEWS.PY

"""


from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import ListadoUsuario, RegistrarUsuario, EditarUsuario, EliminarUsuario

"""Creamos las rutas de las vistas para los templates

    app_name: Nombre de la aplicacion
    path: Ruta donde crearemos la url
    <int:pk>: Asignamos el id para su actualizacion o eliminacion
"""


app_name = "usuario"

urlpatterns = [
    path('listado_usuario/', login_required(ListadoUsuario.as_view()), name='listar_usuarios'),
    path('registrar_usuario/', login_required(RegistrarUsuario.as_view()), name='registrar_usuario'),
    path('editar_usuario/<int:pk>/', login_required(EditarUsuario.as_view()), name='editar_usuario'),
    path('eliminar_usuario/<int:pk>/', login_required(EliminarUsuario.as_view()), name='eliminar_usuario'),
]

templates/busquedaInventario.html
{% extends 'index.html' %}
{% load static %}
{% block extrahead %}
<!-- DataTables -->
<link rel="stylesheet"
  href="{% static 'lib/AdminLTE-3.1.0/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet"
  href="{% static 'lib/AdminLTE-3.1.0/plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
<link rel="stylesheet"
  href="{% static 'lib/AdminLTE-3.1.0/plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
{% endblock extrahead %}

{% block contenido %}

<div class="content">
  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <h2 class="text-center display-4">Busqueda</h2>
      <div class="row">
        <div class="col-md-8 offset-md-2">
          <form method="GET">
            <div class="input-group">
              <input type="search" class="form-control form-control-lg" placeholder="Ingrese bien Mueble" name="buscar">
              <div class="input-group-append">
                <button type="submit" class="btn btn-lg btn-default">
                  <i class="fa fa-search"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
</div>

{% if resultado %}

<!-- Main content -->
<section class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <!-- /.card-header -->
          <div class="card-body">
            <table id="busqueda" class="table table-bordered table-hover">
              <thead>
                <tr>
                  <th scope="col" style="width: 20%">N° PROVISIONAL DEL BIEN</th>
                  <th scope="col" style="width: 20%">NOMBRE</th>
                  <th scope="col" style="width: 20%">DESCRIPCION</th>
                  <th scope="col" style="width: 20%">CARACTERISTICAS</th>
                  <th scope="col" style="width: 20%">ESTADO</th>
                  <th scope="col" style="width: 20%">UBICACION</th>
                  <th scope="col" style="width: 20%">OBSERVACION</th>
                </tr>
              </thead>
              <tbody>
                {% for r in resultado %}
                <tr>
                  <td>{{ r.codigoDelBien }}</td>
                  <td>{{ r.nombre }}</td>
                  <td>{{ r.descripcion }}</td>
                  <td>{{ r.caracteristica }}</td>
                  <td>{{ r.estado }}</td>
                  <td>{{ r.departamento}}</td>
                  <td>{{ r.observacion }}</td>
                </tr>
                {% endfor %}

              </tbody>
            </table>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container-fluid -->
</section>
<!-- /.content -->

{% endif %}

{% endblock contenido %}

{% block extrajs %}
<!-- jQuery -->
<script src="{% static 'lib/AdminLTE-3.1.0/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'lib/AdminLTE-3.1.0/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- DataTables  & Plugins -->
<script src="{% static 'lib/AdminLTE-3.1.0/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'lib/AdminLTE-3.1.0/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'lib/AdminLTE-3.1.0/plugins/datatables-responsive/js/dataTables.responsive.min.js' %}">
</script>
<script src="{% static 'lib/AdminLTE-3.1.0/plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}">
</script>
<script src="{% static 'lib/AdminLTE-3.1.0/plugins/datatables-buttons/js/dataTables.buttons.min.js' %}">
</script>
<script src="{% static 'lib/AdminLTE-3.1.0/plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}">
</script>

<script>
  $(function () {
    $('#busqueda').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>

{% endblock extrajs %}

templates/eliminar.html
{% extends 'index.html' %}
{% load static %}

{% block contenido %}

<form method="POST">
  <div class="card card-default">
    <div class="card-header">
      <h3 class="card-title">
        <i class="fas fa-plus"></i>
        {{ titulo_form }}
      </h3>
    </div>
    <div class="card-body">
      {% csrf_token %}
      <h5><i class="icon fas fa-ban"></i> Notificacion!</h5>
      <div class="alert alert-danger alert-dismissible">
        ¿Estas seguro de eliminar el registro "{{ object.nombre|upper }}"?
      </div>
      <button type="submit" class="btn btn-danger"> Confirmar </button>
      <a href="{{ lista_url }}"><button type="button" class="btn btn-primary"> Cancelar </button></a>
    </div>
  </div>
</form>

{% endblock contenido %}

templates/footer.html
 <!-- Main Footer -->
  <footer class="main-footer bg-red">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Inventario Bienes Muebles Minhvi
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2021</strong> Todos los Derechos Reservados
  </footer>

templates/form_base.html
{% extends 'index.html' %} 

{% block contenido %}

<form method="POST" action=".">
  <div class="card-header">
    <h3 class="card-title">
      <i class="fas fa-plus"></i>
      {{ titulo_form }}
    </h3>
  </div>

  <div class="card-body">
    {% csrf_token %} 
    {% for field in form.visible_fields %}
    <div class="form-group">
      <label for="email"> {{ field.label }} </label>
      {{ field }} 
      {% endfor %}
    </div>
  </div>

  <div class="card-footer">
    <button type="submit" class="btn btn-primary btn-flat btnTest">
      <i class="fas fa-save"></i> {{ titulo_accion }}
    </button>
    <a href="{{ lista_url }}"><button type="button" class="btn btn-danger"> Cancelar </button></a>
  </div>
</form>

<!-- Mensaje de Errores -->
<script>
  {% if form.errors %}

  let errors = "";
      {% for field in form %}
          {% for error in field.errors %}
          errors += "{{ error }}\n";
          {% endfor %}
      {% endfor %}

    Swal.fire({
        title: 'Error',
        text: errors,
        icon: 'error',
    })

  {% endif %}
</script>

{% endblock contenido %}

templates/form_base_usuarios.html
{% extends 'index.html' %} 

{% block contenido %}

<form method="POST" action=".">
  <div class="card-header">
    <h3 class="card-title">
      <i class="fas fa-plus"></i>
      {{ titulo_form }}
    </h3>
  </div>

  <div class="card-body">
    {% csrf_token %}
    {{ form.as_p }}
  </div>

  <div class="card-footer">
    <button type="submit" class="btn btn-primary btn-flat btnTest">
      <i class="fas fa-save"></i> {{ titulo_accion }}
    </button>
    <a href="{{ lista_url }}"><button type="button" class="btn btn-danger"> Cancelar </button></a>
  </div>
</form>

<!-- Mensaje de Errores -->

<script>

  {% if form.errors %}
  let errors = "";
      {% for field in form %}
          {% for error in field.errors %}
          errors += "{{ error }}\n";
          {% endfor %}
      {% endfor %}

    Swal.fire({
        title: 'Error',
        text: errors,
        icon: 'error',
    })
  {% endif %}

</script>

{% endblock contenido %}

templates/header.html
<nav class="main-header navbar navbar-expand navbar-dark navbar-red">
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"
        ><i class="fas fa-bars"></i
      ></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="{% url 'index' %}" class="nav-link">Inicio</a>
    </li>
  </ul>
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'logout' %}">
        <i class="fas fa-power-off" aria-hidden="true"></i>
      </a>
    </li>
  </ul>
</nav>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Inventario Minhvi</title>
    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon_GMVV_2.ico' %}">

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback" />
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.1.0/plugins/fontawesome-free/css/all.min.css' %}" />
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.1.0/css/adminlte.min.css' %}" />
    <!-- jQuery -->
    <script src="{% static 'lib/adminlte-3.1.0/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/adminlte-3.1.0/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/adminlte-3.1.0/js/adminlte.min.js' %}"></script>
    <!-- sweet alert Offline -->
    <script src="{% static 'lib/sweetAlert2/dist/sweetalert2.all.min.js' %}"></script>

    {% block extrahead %}
    {% endblock extrahead %}

</head>

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Header -->
        {% include 'header.html' %}
        <!-- Sidebar -->
        {% include 'sidebar.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content">
                <div class="container-fluid">
                    {% block contenido %}

                    {% include "opciones_inicio.html" %}

                    {% endblock contenido %}
                </div>
            </div>
        </div>
    </div>
    <!-- Footer -->
    {% include 'footer.html' %}

    {% block extrajs %}
    {% endblock extrajs %}

</body>

</html>

templates/lista.html
{% extends 'index.html' %}
{% load static %}
{% block extrahead %}
<!-- Datatables -->
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" />

<!--datables CSS básico-->
<link rel="stylesheet" type="text/css" href="{% static 'lib/datatables/datatables.min.css' %}" />
<!--datables estilo bootstrap 4 CSS-->
<link rel="stylesheet" type="text/css"
  href="{% static 'lib/datatables/DataTables-1.11.3/css/dataTables.bootstrap4.min.css' %}" />
{% endblock extrahead %}

{% block contenido %}

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="content-header">
        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">{{ titulo }}</h1>
            </div>
          </div>
        </div>
      </div>
      <div class="table-responsive">
        <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
          <thead>
            {% block columnas %}

            {% endblock columnas %}
          </thead>
          <tbody>
            {% block filas %}

            {% endblock filas %}
          </tbody>
        </table>
      </div>
      <!-- Nuevo Registro -->
      <div class="card-footer">
        <a href="{{ crear_url }}" class="btn btn-primary btn-flat btnTest">
          <i class="fas fa-plus"></i> Nuevo Registro</a>
      </div>
      <!-- Fin Nuevo Registro -->
    </div>
  </div>
</div>

<!-- datatables JS -->
<script type="text/javascript" src="{% static 'lib/datatables/datatables.min.js' %}"></script>

<!-- para usar botones en datatables JS -->
<script src="{% static 'lib/datatables/Buttons-2.0.1/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'lib/datatables/JSZip-2.5.0/jszip.min.js' %}"></script>
<script src="{% static 'lib/datatables/pdfmake-0.1.36/pdfmake.min.js' %}"></script>
<script src="{% static 'lib/datatables/pdfmake-0.1.36/vfs_fonts.js' %}"></script>
<script src="{% static 'lib/datatables/Buttons-2.0.1/js/buttons.html5.min.js' %}"></script>

<!-- código JS propìo-->
<script type="text/javascript" src="{% static 'lib/main.js' %}"></script>

{% endblock contenido %}

templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Ingreso</title>

    <link rel="shortcut icon" href="{% static 'img/favicon_GMVV_2.ico' %}">

    <!-- Google Font: Source Sans Pro -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"
    />
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="{% static 'lib/adminlte-3.1.0/plugins/fontawesome-free/css/all.min.css' %}"
    />
    <!-- Theme style -->
    <link
      rel="stylesheet"
      href="{% static 'lib/adminlte-3.1.0/css/adminlte.min.css' %}"
    />
    <!-- sweet alert Offline -->
    <script src="{% static 'lib/sweetAlert2/dist/sweetalert2.all.min.js' %}"></script>

    <!-- Estilo personal -->
    <link
      rel="stylesheet"
      href="{% static 'lib/styles.css' %}"
    />

  </head>
  
  <body class="hold-transition login-page">
  
    <div class="login-box">
      <div class="login-logo">
        <a href="#"><b>Bienes</b> Muebles</a>
      </div>
      <!-- /.login-logo -->
      <div class="card">
        <div class="card-body login-card-body">
          <p class="login-box-msg">Inicio Sesión</p>

          <form action="" method="POST">
            {% csrf_token %}
            
            <!-- Inicio del Mensaje de errores -->
            {% if form.errors %}
            <script>
              Swal.fire({
                title: 'Error Inicio Sesion',
                text: 'Introduzca un nombre de usuario y clave correctos. Observe que ambos campos pueden ser sensibles a mayúsculas.',
                icon: 'error',
              })
            </script>
            {% endif %}
            <!-- Fin del Mensaje de errores -->

            <div class="input-group mb-3">
              <!-- este form viene de forms.py de la app usuario -->
              {{ form.username }}
              <div class="input-group-append">
                <div class="input-group-text">
                  <span class="fas fa-user"></span>
                </div>
              </div>
            </div>
            <div class="input-group mb-3">
              <!-- este form viene de forms.py de la app usuario -->
              {{ form.password }}
              <div class="input-group-append">
                <div class="input-group-text">
                  <span class="fas fa-lock"></span>
                </div>
              </div>
            </div>
            <div class="col">
              <button type="submit" class="btn bg-red btn-block">
                Ingresar
              </button>
              <!-- /.col -->
            </div>
            
          </form>
        </div>
        <!-- /.login-card-body -->
      </div>
    </div>
    <!-- /.login-box -->

    <!-- jQuery -->
    <script src="{% static 'lib/adminlte-3.1.0/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/adminlte-3.1.0/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/adminlte-3.1.0/js/adminlte.min.js' %}"></script>

  </body>
</html>

templates/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-light-primary elevation-4">
  <a href="#" class="brand-link">
    <img src="{% static 'img/logo-2.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
      style="opacity: 0.8" />
    <span class="brand-text font-weight-light">MINHVI</span>
  </a>
  <div class="sidebar">
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="{% static 'lib/AdminLTE-3.1.0/img/avatar.png' %}" class="img-circle elevation-2" alt="User Image" />
      </div>
      <div class="info">
        <a href="" class="d-block">{{ user.username|upper }}</a>
      </div>
    </div>
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-header">INVENTARIO</li>

        {% if request.user.is_staff %}
        <li class="nav-item">
          <a href="{% url 'usuario:listar_usuarios' %}" class="nav-link">
            <i class="nav-icon fas fa-users"></i>
            <p>Usuarios</p>
          </a>
        </li>
        {% endif %}

        <li class="nav-item">
          <a href="{% url 'app:lista_departamento' %}" class="nav-link">
            <i class="nav-icon fas fa-building"></i>
            <p>Departamento</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'app:lista_jefe_departamento' %}" class="nav-link">
            <i class="nav-icon fas fa-address-card"></i>
            <p>Jefe departamento</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'app:lista_responsable_patrimonio' %}" class="nav-link">
            <i class="nav-icon fas fa-user"></i>
            <p>Responsable</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'app:lista_direccion_bienes' %}" class="nav-link">
            <i class="nav-icon fas fa-book"></i>
            <p>Dirección bienes</p>
          </a>
        </li>

        <li class="nav-item">
          <a href="{% url 'app:busqueda_inventario' %}" class="nav-link">
            <i class="nav-icon fas fa-search"></i>
            <p>Busqueda</p>
          </a>
        </li>
        <!-- Inicio menu desplegable de inventario -->
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-archive"></i>
            <p>
              Inventarios
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <!-- Inicio 1er departamento -->
          <ul class="nav nav-treeview" style="display: none">
            <li class="nav-item">
              <a href="{% url 'app:lista_inventario' %}" class="nav-link">
                <i class="nav-icon fas fa-dot-circle"></i>
                <p>Administración</p>
              </a>
            </li>
          </ul>
          <!-- Fin 1er departamento -->

          <!-- Inicio 2do departamento -->
          <ul class="nav nav-treeview" style="display: none">
            <li class="nav-item">
              <a href="{% url 'app:lista_inventario_asesoria_legal' %}" class="nav-link">
                <i class="nav-icon fas fa-dot-circle"></i>
                <p>Asesoria Legal</p>
              </a>
            </li>
          </ul>
          <!-- Fin 2do departamento -->

          <!-- Inicio 3er departamento -->
          <ul class="nav nav-treeview" style="display: none">
            <li class="nav-item">
              <a href="{% url 'app:lista_inventario_atencion_ciudadano' %}" class="nav-link">
                <i class="nav-icon fas fa-dot-circle"></i>
                <p>Atencion al Ciudadano</p>
              </a>
            </li>
          </ul>
          <!-- Fin 3er departamento -->

          <!-- Inicio 4to departamento -->
          <ul class="nav nav-treeview" style="display: none">
            <li class="nav-item">
              <a href="{% url 'app:lista_inventario_banhavi_cobranza' %}" class="nav-link">
                <i class="nav-icon fas fa-dot-circle"></i>
                <p>Banhavi Cobranza</p>
              </a>
            </li>
          </ul>
          <!-- Fin 4to departamento -->

          <!-- Inicio 5to departamento -->
          <ul class="nav nav-treeview" style="display: none">
            <li class="nav-item">
              <a href="{% url 'app:lista_inventario_banhavi_fao' %}" class="nav-link">
                <i class="nav-icon fas fa-dot-circle"></i>
                <p>Banhavi FAO</p>
              </a>
            </li>
          </ul>
          <!-- Fin 5to departamento -->

          <!-- Inicio 6to departamento -->
          <ul class="nav nav-treeview" style="display: none">
            <li class="nav-item">
              <a href="{% url 'app:lista_inventario_bnbt' %}" class="nav-link">
                <i class="nav-icon fas fa-dot-circle"></i>
                <p>Barrio Nuevo Barrio Tricolor</p>
              </a>
            </li>
          </ul>
          <!-- Fin 6to departamento -->

          <!-- Inicio 7mo departamento -->
          <ul class="nav nav-treeview" style="display: none">
            <li class="nav-item">
              <a href="{% url 'app:lista_inventario_direccion' %}" class="nav-link">
                <i class="nav-icon fas fa-dot-circle"></i>
                <p>Dirección</p>
              </a>
            </li>
          </ul>
          <!-- Fin 7mo departamento -->

          <!-- Inicio 8vo departamento -->
          <ul class="nav nav-treeview" style="display: none">
            <li class="nav-item">
              <a href="{% url 'app:lista_inventario_gestion_humana' %}" class="nav-link">
                <i class="nav-icon fas fa-dot-circle"></i>
                <p>Gestion Humana</p>
              </a>
            </li>
          </ul>
          <!-- Fin 8vo departamento -->

          <!-- Inicio 9no departamento -->
          <ul class="nav nav-treeview" style="display: none">
            <li class="nav-item">
              <a href="{% url 'app:lista_inventario_inmobiliaria_nacional' %}" class="nav-link">
                <i class="nav-icon fas fa-dot-circle"></i>
                <p>Inmobiliaria Nacional</p>
              </a>
            </li>
          </ul>
          <!-- Fin 9no departamento -->

          <!-- Inicio 10mo departamento -->
          <ul class="nav nav-treeview" style="display: none">
            <li class="nav-item">
              <a href="{% url 'app:lista_inventario_intu' %}" class="nav-link">
                <i class="nav-icon fas fa-dot-circle"></i>
                <p>Intu</p>
              </a>
            </li>
          </ul>
          <!-- Fin 10mo departamento -->

          <!-- Inicio 11 departamento -->
          <ul class="nav nav-treeview" style="display: none">
            <li class="nav-item">
              <a href="{% url 'app:lista_inventario_obras' %}" class="nav-link">
                <i class="nav-icon fas fa-dot-circle"></i>
                <p>Obras</p>
              </a>
            </li>
          </ul>
          <!-- Fin 11 departamento -->

          <!-- Inicio 12 departamento -->
          <ul class="nav nav-treeview" style="display: none">
            <li class="nav-item">
              <a href="{% url 'app:lista_inventario_redes_populares' %}" class="nav-link">
                <i class="nav-icon fas fa-dot-circle"></i>
                <p>Redes Populares</p>
              </a>
            </li>
          </ul>
          <!-- Fin 12 departamento -->

          <!-- Inicio 13 departamento -->
          <ul class="nav nav-treeview" style="display: none">
            <li class="nav-item">
              <a href="{% url 'app:lista_inventario_sala_situacional' %}" class="nav-link">
                <i class="nav-icon fas fa-dot-circle"></i>
                <p>Sala Situacional</p>
              </a>
            </li>
          </ul>
          <!-- Fin 13 departamento -->

          <!-- Inicio 14 departamento -->
          <ul class="nav nav-treeview" style="display: none">
            <li class="nav-item">
              <a href="{% url 'app:lista_inventario_saren' %}" class="nav-link">
                <i class="nav-icon fas fa-dot-circle"></i>
                <p>Saren</p>
              </a>
            </li>
          </ul>
          <!-- Fin 14 departamento -->

          <!-- Inicio 15 departamento -->
          <ul class="nav nav-treeview" style="display: none">
            <li class="nav-item">
              <a href="{% url 'app:lista_inventario_jubilados' %}" class="nav-link">
                <i class="nav-icon fas fa-dot-circle"></i>
                <p>Jubilados</p>
              </a>
            </li>
          </ul>
          <!-- Fin 15 departamento -->

          <!-- Inicio 16 departamento -->
          <ul class="nav nav-treeview" style="display: none">
            <li class="nav-item">
              <a href="{% url 'app:lista_inventario_sistemas' %}" class="nav-link">
                <i class="nav-icon fas fa-dot-circle"></i>
                <p>Sistemas</p>
              </a>
            </li>
          </ul>
          <!-- Fin 16 departamento -->

          <!-- Inicio 17 departamento -->
          <ul class="nav nav-treeview" style="display: none">
            <li class="nav-item">
              <a href="{% url 'app:lista_inventario_sunavi' %}" class="nav-link">
                <i class="nav-icon fas fa-dot-circle"></i>
                <p>Sunavi</p>
              </a>
            </li>
          </ul>
          <!-- Fin 17 departamento -->

          <!-- Inicio 18 departamento -->
          <ul class="nav nav-treeview" style="display: none">
            <li class="nav-item">
              <a href="{% url 'app:lista_inventario_vivienda' %}" class="nav-link">
                <i class="nav-icon fas fa-dot-circle"></i>
                <p>Vivienda</p>
              </a>
            </li>
          </ul>
          <!-- Fin 18 departamento -->
        </li>
        <!-- Fin menu desplegable de inventario -->
      </ul>
    </nav>
  </div>
</aside>